let num1=["apple","mango","cherry"];
console.log(num1);
let num2=["banana",1];
console.log(num2);
console.log(num1[0][4]);
console.log(num1[0].length);
console.log(num2[0].length);
console.log(num1[3]="orange");
console.log(num1[3]);
console.log(num1[2]);
console.log(num2.length);
console.log(num1.unshift("grapes"));
console.log(num1.pop());
console.log(num1.push("guava"));
console.log(num1.shift());
console.log(num1.shift());
console.log(num1.pop());
console.log(num1.indexOf("mango"));
let num3=num1+num2;
console.log(num3);
console.log(num1.slice(-5));
console.log(num1.slice(1,3));
console.log(num1.splice(1,2));
num2.splice(1,0,"watermelon","stawberry");
console.log(num2);
num4=[5,3,9,25]
console.log(num4.sort());